export const GET_PLAYER_RACE = 'GET_PLAYER_RACE';
export const GET_PLAYER_CLASS = 'GET_PLAYER_CLASS';
export const GET_PLAYER_AVATAR = 'GET_PLAYER_AVATAR';
export const GET_PLAYER_BACKGROUND = 'GET_PLAYER_BACKGROUND';
