export const GET_PLAYER_EXTRA_LANGUAGE = 'GET_PLAYER_EXTRA_LANGUAGE';
export const GET_PLAYER_CANTRIPS = 'GET_PLAYER_CANTRIPS';
export const GET_PLAYER_TOOL_PROFICIENCY = 'GET_PLAYER_TOOL_PROFICIENCY';
export const GET_PLAYER_RACE = 'GET_PLAYER_RACE';
export const GET_PLAYER_CLASS = 'GET_PLAYER_CLASS';
