export const GET_PLAYER_RACE = 'GET_PLAYER_RACE';
export const GET_PLAYER_CLASS = 'GET_PLAYER_CLASS';
export const GET_PLAYER_AVATAR = 'GET_PLAYER_AVATAR';
export const GET_PLAYER_BACKGROUND = 'GET_PLAYER_BACKGROUND';
export const ADD_PLAYER = 'ADD_PLAYER';
export const ADD_PLAYER_ID = 'ADD_PLAYER_ID';
export const DELETE_PLAYER = 'DELETE_PLAYER';
export const CLEAR_PLAYER_STATE = 'CLEAR_PLAYER_STATE';
